spring:
  cloud:
    function:
      definition: CatalogEvent;ProductEvent
    stream:
      bindings:
        CatalogEvent-out-0:
          destination: finetech.sales.catalog
        ProductEvent-out-0:
          destination: finetech.sales.product
logging:
  level:
    root: info
    org:
      springframework: info

